In [1]:
import sys
from pathlib import Path
sys.path.append(str(Path.cwd().parent))

from utils import dados, pivot, unpivot

In [2]:
# Teste

# Carrega dados
df_original, metadados, variaveis = dados(r"data\input\dados_brutos.xlsx")

# Pivoteia
df_pivotado = pivot(df_original, metadados, variaveis)

# Despivoteia
df_restaurado = unpivot(df_pivotado)

# Verifica se voltou ao original
print(df_original.equals(df_restaurado))  # Deve ser True

False

In [3]:
df_original.head()

,Data,Estatistica,COR,TURB.,pH,ALC.,AC.,O.C.,DBO,O.D.,...,Cond.,Amonia,Surfact.,Cianobacteria,S.T.,C.T.,C.F.,Clorofila,F,Fenol
0,2009-01-01,Min.,200.0,64.0,7.0,29.0,3.0,6.3,NaN,2.0,...,131.0,NaN,NaN,6600.0,NaN,50000.0,23000,2.23,0.12,NaN
1,2009-01-01,Med.,432.0,131.0,7.2,34.0,5.0,6.8,NaN,3.5,...,145.0,NaN,NaN,6850.0,NaN,50000.0,23000,11.35,0.16,NaN
2,2009-01-01,Max.,690.0,241.0,7.4,38.0,8.0,7.5,NaN,4.8,...,156.0,NaN,NaN,7100.0,NaN,50000.0,23000,22.32,0.19,NaN
3,2009-02-01,Min.,393.0,72.0,6.5,29.0,6.0,5.9,NaN,2.8,...,128.0,NaN,NaN,1100.0,NaN,240000.0,30000,6.69,0.12,NaN
4,2009-02-01,Med.,868.0,238.0,7.1,31.0,7.0,7.2,NaN,4.1,...,133.0,NaN,NaN,2100.0,NaN,240000.0,30000,7.81,0.16,NaN

In [4]:
df_pivotado.head()

,Data,COR_Min.,COR_Med.,COR_Max.,TURB._Min.,TURB._Med.,TURB._Max.,pH_Min.,pH_Med.,pH_Max.,...,C.F._Max.,Clorofila_Min.,Clorofila_Med.,Clorofila_Max.,F_Min.,F_Med.,F_Max.,Fenol_Min.,Fenol_Med.,Fenol_Max.
0,2009-01-01,200.0,432.0,690.0,64.0,131.0,241.0,7.0,7.2,7.4,...,23000,2.23,11.35,22.32,0.12,0.16,0.19,NaN,NaN,NaN
1,2009-02-01,393.0,868.0,1110.0,72.0,238.0,329.0,6.5,7.1,7.5,...,30000,6.69,7.81,8.92,0.12,0.16,0.19,NaN,NaN,NaN
2,2009-03-01,75.0,158.0,320.0,20.0,63.0,163.0,7.4,7.4,7.5,...,170000,0.56,7.62,22.32,0.12,0.16,0.19,NaN,NaN,NaN
3,2009-04-01,40.0,63.0,90.0,15.0,36.0,47.0,7.3,7.4,7.5,...,17000,8.03,9.93,12.05,0.12,0.16,0.19,NaN,NaN,NaN
4,2009-05-01,23.0,33.0,40.0,12.0,14.0,17.0,7.1,7.3,7.4,...,8000,8.03,18.97,43.75,0.12,0.16,0.19,NaN,NaN,NaN

In [5]:
df_restaurado.head()

,Data,Estatistica,AC.,ALC.,Amonia,C.F.,C.T.,COR,Cianobacteria,Cl,...,Fenol,Mn,N,O.C.,O.D.,P,S.T.,Surfact.,TURB.,pH
0,2009-01-01,Min.,3.0,29.0,NaN,23000,50000.0,200.0,6600.0,16.0,...,NaN,0.09,NaN,6.3,2.0,NaN,NaN,NaN,64.0,7.0
1,2009-01-01,Med.,5.0,34.0,NaN,23000,50000.0,432.0,6850.0,23.0,...,NaN,0.17,NaN,6.8,3.5,NaN,NaN,NaN,131.0,7.2
2,2009-01-01,Max.,8.0,38.0,NaN,23000,50000.0,690.0,7100.0,33.0,...,NaN,0.32,NaN,7.5,4.8,NaN,NaN,NaN,241.0,7.4
3,2009-02-01,Min.,6.0,29.0,NaN,30000,240000.0,393.0,1100.0,20.0,...,NaN,0.08,NaN,5.9,2.8,NaN,NaN,NaN,72.0,6.5
4,2009-02-01,Med.,7.0,31.0,NaN,30000,240000.0,868.0,2100.0,21.0,...,NaN,0.12,NaN,7.2,4.1,NaN,NaN,NaN,238.0,7.1