In [ ]:
import pandas as pd
import os
from datetime import datetime

In [2]:
arquivo_entrada = "C:\_Master\programacao\Guilherme-Betta\IC2\data\in\dadosBrutosProntos.xlsx"

dados = pd.read_excel(arquivo_entrada)

metadados = ['Data', 'Estatistica', 'data_normalizada']

variaveis = [cols for cols in dados.columns if cols not in metadados]

dados.head()

<>:1: SyntaxWarning: "\_" is an invalid escape sequence. Such sequences will not work in the future. Did you mean "\\_"? A raw string is also an option.
<>:1: SyntaxWarning: "\_" is an invalid escape sequence. Such sequences will not work in the future. Did you mean "\\_"? A raw string is also an option.
C:\Users\Wary\AppData\Local\Temp\ipykernel_13840\3077928949.py:1: SyntaxWarning: "\_" is an invalid escape sequence. Such sequences will not work in the future. Did you mean "\\_"? A raw string is also an option.
  arquivo_entrada = "C:\_Master\programacao\Guilherme-Betta\IC2\data\in\dadosBrutosProntos.xlsx"

,Data,data_normalizada,COR_Max.,COR_Med.,COR_Min.,TURB._Max.,TURB._Med.,TURB._Min.,pH_Max.,pH_Med.,...,C.F._Min.,Clorofila_Max.,Clorofila_Med.,Clorofila_Min.,F_Max.,F_Med.,F_Min.,Fenol_Max.,Fenol_Med.,Fenol_Min.
0,2009-01-01,2009-01-01,690.0,432.0,200.0,241.0,131.0,64.0,7.4,7.2,...,23000.0,22.32,11.35,2.23,0.19,0.16,0.12,NaN,NaN,NaN
1,2009-02-01,2009-02-01,1110.0,868.0,393.0,329.0,238.0,72.0,7.5,7.1,...,30000.0,8.92,7.81,6.69,0.19,0.16,0.12,NaN,NaN,NaN
2,2009-03-01,2009-03-01,320.0,158.0,75.0,163.0,63.0,20.0,7.5,7.4,...,170000.0,22.32,7.62,0.56,0.19,0.16,0.12,NaN,NaN,NaN
3,2009-04-01,2009-04-01,90.0,63.0,40.0,47.0,36.0,15.0,7.5,7.4,...,17000.0,12.05,9.93,8.03,0.19,0.16,0.12,NaN,NaN,NaN
4,2009-05-01,2009-05-01,40.0,33.0,23.0,17.0,14.0,12.0,7.4,7.3,...,1100.0,43.75,18.97,8.03,0.19,0.16,0.12,NaN,NaN,NaN

# Remoção de dados corrompidos (não numéricos)

In [3]:
### Dados Corrompidos

for coluna in dados[variaveis]:
    dados[coluna] = pd.to_numeric(dados[coluna], errors='coerce')   # Remove valores de dtype != float das colunas na lista "variaveis"
    
dados.select_dtypes(exclude=float)

          Data data_normalizada
0   2009-01-01       2009-01-01
1   2009-02-01       2009-02-01
2   2009-03-01       2009-03-01
3   2009-04-01       2009-04-01
4   2009-05-01       2009-05-01
..         ...              ...
187 2024-08-01       2024-08-01
188 2024-09-01       2024-09-01
189 2024-10-01       2024-10-01
190 2024-11-01       2024-11-01
191 2024-12-01       2024-12-01

[192 rows x 2 columns]

# Remoção de colunas com 30% de dados faltantes

In [ ]:
limpeza = dados.dropna(axis=1, thresh=len(dados)*0.3)   # Elimina colunas com metade (ou mais) de dados faltantes

limpeza.head()

,Data,data_normalizada,COR_Max.,COR_Med.,COR_Min.,TURB._Max.,TURB._Med.,TURB._Min.,pH_Max.,pH_Med.,...,Cianobacteria_Min.,C.F._Max.,C.F._Med.,C.F._Min.,Clorofila_Max.,Clorofila_Med.,Clorofila_Min.,F_Max.,F_Med.,F_Min.
0,2009-01-01,2009-01-01,690.0,432.0,200.0,241.0,131.0,64.0,7.4,7.2,...,6600.0,23000.0,23000.0,23000.0,22.32,11.35,2.23,0.19,0.16,0.12
1,2009-02-01,2009-02-01,1110.0,868.0,393.0,329.0,238.0,72.0,7.5,7.1,...,1100.0,30000.0,30000.0,30000.0,8.92,7.81,6.69,0.19,0.16,0.12
2,2009-03-01,2009-03-01,320.0,158.0,75.0,163.0,63.0,20.0,7.5,7.4,...,611.0,170000.0,170000.0,170000.0,22.32,7.62,0.56,0.19,0.16,0.12
3,2009-04-01,2009-04-01,90.0,63.0,40.0,47.0,36.0,15.0,7.5,7.4,...,2525.0,17000.0,17000.0,17000.0,12.05,9.93,8.03,0.19,0.16,0.12
4,2009-05-01,2009-05-01,40.0,33.0,23.0,17.0,14.0,12.0,7.4,7.3,...,4348.0,8000.0,4550.0,1100.0,43.75,18.97,8.03,0.19,0.16,0.12

# Salvamento de arquivo

In [6]:
pasta_saida = "C:\_Master\programacao\Guilherme-Betta\IC2\data\out" # Cria uma variável para guardar o caminho de onde o arquivo resultante será salvo

os.makedirs(pasta_saida, exist_ok=True) # Passo necessário para o python salvar o arquivo

nome_arquivo = f"describe()_{datetime.now().strftime('%Y%m%d_%H%M%S')}.xlsx"   # Gera o nome do arquivo de saida com timestamp de quando foi criado

caminho_saida = os.path.join(pasta_saida, nome_arquivo) # Cria o diretório para salvar o arquivo caso ela ainda não exista

limpeza.to_excel(caminho_saida, engine='openpyxl', index=True)   # Gera o arquivo de saida

<>:1: SyntaxWarning: "\_" is an invalid escape sequence. Such sequences will not work in the future. Did you mean "\\_"? A raw string is also an option.
<>:1: SyntaxWarning: "\_" is an invalid escape sequence. Such sequences will not work in the future. Did you mean "\\_"? A raw string is also an option.
C:\Users\Wary\AppData\Local\Temp\ipykernel_13840\4181646116.py:1: SyntaxWarning: "\_" is an invalid escape sequence. Such sequences will not work in the future. Did you mean "\\_"? A raw string is also an option.
  pasta_saida = "C:\_Master\programacao\Guilherme-Betta\IC2\data\out" # Cria uma variável para guardar o caminho de onde o arquivo resultante será salvo