In [ ]:
import pandas as pd
import os 
from datetime import datetime

In [6]:
dadosBrutos = pd.read_excel('C:\_Master\programacao\Guilherme-Betta\IC2\data\in\dadosBrutosProntos.xlsx')

<>:1: SyntaxWarning: "\_" is an invalid escape sequence. Such sequences will not work in the future. Did you mean "\\_"? A raw string is also an option.
<>:1: SyntaxWarning: "\_" is an invalid escape sequence. Such sequences will not work in the future. Did you mean "\\_"? A raw string is also an option.
C:\Users\Wary\AppData\Local\Temp\ipykernel_29096\3077681265.py:1: SyntaxWarning: "\_" is an invalid escape sequence. Such sequences will not work in the future. Did you mean "\\_"? A raw string is also an option.
  dadosBrutos = pd.read_excel('C:\_Master\programacao\Guilherme-Betta\IC2\data\in\dadosBrutosProntos.xlsx')

In [8]:
describe = dadosBrutos.describe()
print(describe)

                      Data     data_normalizada     COR_Max.    COR_Med.  \
count                  192                  192   191.000000  191.000000
mean   2016-12-15 17:00:00  2016-12-15 17:00:00   269.863874  120.476440
min    2009-01-01 00:00:00  2009-01-01 00:00:00    35.000000   28.000000
25%    2012-12-24 06:00:00  2012-12-24 06:00:00    83.000000   54.500000
50%    2016-12-16 12:00:00  2016-12-16 12:00:00   169.000000   77.000000
75%    2020-12-08 18:00:00  2020-12-08 18:00:00   369.000000  153.000000
max    2024-12-01 00:00:00  2024-12-01 00:00:00  1650.000000  868.000000
std                    NaN                  NaN   269.943819  110.340946

         COR_Min.   TURB._Max.  TURB._Med.  TURB._Min.     pH_Max.  \
count  191.000000   191.000000  191.000000  191.000000  191.000000
mean    57.418848   226.607330   63.575916   16.476440    7.529843
min      4.000000     6.000000    4.000000    1.000000    7.200000
25%     32.000000    21.500000   10.000000    5.000000    7.400000
50%     46.000000    78.000000   28.000000    9.000000    7.500000
75%     64.000000   337.500000   89.000000   16.000000    7.600000
max    393.000000  1200.000000  401.000000  210.000000    8.100000
std     47.856941   292.178006   76.455376   24.664874    0.207490

          pH_Med.  ...     C.T._Med.     C.T._Min.      C.F._Med.  \
count  191.000000  ...  7.500000e+01  7.500000e+01     154.000000
mean     7.324607  ...  3.032418e+05  2.534040e+05   23989.480519
min      7.000000  ...  0.000000e+00  0.000000e+00       0.000000
25%      7.200000  ...  3.000000e+04  3.000000e+04    2325.000000
50%      7.300000  ...  1.100000e+05  7.000000e+04    5700.000000
75%      7.400000  ...  3.000000e+05  2.400000e+05   19000.000000
max      7.900000  ...  3.000000e+06  3.000000e+06  300000.000000
std      0.180560  ...  5.231445e+05  5.098040e+05   50506.968194

           C.F._Min.  Clorofila_Max.  Clorofila_Med.  Clorofila_Min.  \
count     154.000000      177.000000      177.000000      177.000000
mean    20536.233766       37.190621       36.522768       35.897119
min         0.000000        0.000000        0.000000        0.000000
25%      2025.000000       13.390000       12.280000       11.160000
50%      5000.000000       26.340000       24.000000       22.320000
75%     17000.000000       48.210000       46.130000       46.130000
max    300000.000000      509.640000      509.640000      509.640000
std     45609.438968       47.623545       47.799339       48.099987

           F_Max.      F_Med.      F_Min.
count  156.000000  156.000000  156.000000
mean     0.425064    0.295308    0.220192
min      0.000000    0.000000    0.000000
25%      0.280000    0.220000    0.160000
50%      0.380000    0.280000    0.210000
75%      0.500000    0.360000    0.270000
max      1.520000    0.770000    0.730000
std      0.263347    0.137263    0.113850

[8 rows x 70 columns]

In [ ]:
### Dados Ausentes

def calculate_missing_percentage(df):
    missing_by_column = df.isna().sum()
    total_rows = len(df)
    missing_percentage_by_column = (missing_by_column / total_rows * 100).round(2)
    missing_total = df.isna().sum().sum()
    total_elements = df.size
    missing_percentage_total = (missing_total / total_elements * 100).round(2)
    return {
        'by_column': missing_percentage_by_column,
        'total': missing_percentage_total
    }

In [ ]:
calculate_missing_percentage(dados)

In [ ]:
isnull = dadosBrutos.isnull()
isnull.loc()

,Data,data_normalizada,COR_Max.,COR_Med.,COR_Min.,TURB._Max.,TURB._Med.,TURB._Min.,pH_Max.,pH_Med.,...,C.F._Min.,Clorofila_Max.,Clorofila_Med.,Clorofila_Min.,F_Max.,F_Med.,F_Min.,Fenol_Max.,Fenol_Med.,Fenol_Min.
0,False,False,False,False,False,False,False,False,False,False,...,False,False,False,False,False,False,False,True,True,True
1,False,False,False,False,False,False,False,False,False,False,...,False,False,False,False,False,False,False,True,True,True
2,False,False,False,False,False,False,False,False,False,False,...,False,False,False,False,False,False,False,True,True,True
3,False,False,False,False,False,False,False,False,False,False,...,False,False,False,False,False,False,False,True,True,True
4,False,False,False,False,False,False,False,False,False,False,...,False,False,False,False,False,False,False,True,True,True
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
187,False,False,False,False,False,False,False,False,False,False,...,False,False,False,False,False,False,False,True,True,True
188,False,False,False,False,False,False,False,False,False,False,...,True,True,True,True,False,False,False,True,True,True
189,False,False,False,False,False,False,False,False,False,False,...,True,True,True,True,False,False,False,True,True,True
190,False,False,False,False,False,False,False,False,False,False,...,False,False,False,False,False,False,False,True,True,True
191,False,False,True,True,True,True,True,True,True,True,...,True,True,True,True,True,True,True,True,True,True

In [ ]:
# Ir linha a linha somando a quantidade de zeros na linha
# Criar um contador que vai somando a quantidade de zeros em cada coluna
# Append no final do dataframe a linha com esse contador

          Data data_normalizada C.F._Max. Fenol_Max. Fenol_Med. Fenol_Min.
0   2009-01-01       2009-01-01     23000        NaN        NaN        NaN
1   2009-02-01       2009-02-01     30000        NaN        NaN        NaN
2   2009-03-01       2009-03-01    170000        NaN        NaN        NaN
3   2009-04-01       2009-04-01     17000        NaN        NaN        NaN
4   2009-05-01       2009-05-01      8000        NaN        NaN        NaN
..         ...              ...       ...        ...        ...        ...
187 2024-08-01       2024-08-01      2200        NaN        NaN        NaN
188 2024-09-01       2024-09-01       NaN        NaN        NaN        NaN
189 2024-10-01       2024-10-01       NaN        NaN        NaN        NaN
190 2024-11-01       2024-11-01      3000        NaN        NaN        NaN
191 2024-12-01       2024-12-01       NaN        NaN        NaN        NaN

[192 rows x 6 columns]

In [ ]:
dadosBrutos.select_dtypes(exclude= float)   # Permite identificar colunas com valores nao numericos. 
                                            # No caso, sao elas "Data" e "data_normalizada" (esperado), 
                                            # mas tambem "C.F. Max.", "Fenol_Max.", "Fenol_Med." e "Fenol_Min."
                                            # Isso ocorre, pois essas colunas apresentam células com os caracteres "<" ou ">"

          Data data_normalizada C.F._Max. Fenol_Max. Fenol_Med. Fenol_Min.
0   2009-01-01       2009-01-01     23000        NaN        NaN        NaN
1   2009-02-01       2009-02-01     30000        NaN        NaN        NaN
2   2009-03-01       2009-03-01    170000        NaN        NaN        NaN
3   2009-04-01       2009-04-01     17000        NaN        NaN        NaN
4   2009-05-01       2009-05-01      8000        NaN        NaN        NaN
..         ...              ...       ...        ...        ...        ...
187 2024-08-01       2024-08-01      2200        NaN        NaN        NaN
188 2024-09-01       2024-09-01       NaN        NaN        NaN        NaN
189 2024-10-01       2024-10-01       NaN        NaN        NaN        NaN
190 2024-11-01       2024-11-01      3000        NaN        NaN        NaN
191 2024-12-01       2024-12-01       NaN        NaN        NaN        NaN

[192 rows x 6 columns]