In [2]:
import pandas as pd
import os 
from datetime import datetime

In [22]:
dados = pd.read_excel('C:\_Master\programacao\Guilherme-Betta\IC2\data\in\dadosBrutos.xlsx')

dados.info

<>:1: SyntaxWarning: "\_" is an invalid escape sequence. Such sequences will not work in the future. Did you mean "\\_"? A raw string is also an option.
<>:1: SyntaxWarning: "\_" is an invalid escape sequence. Such sequences will not work in the future. Did you mean "\\_"? A raw string is also an option.
C:\Users\Wary\AppData\Local\Temp\ipykernel_26316\865297245.py:1: SyntaxWarning: "\_" is an invalid escape sequence. Such sequences will not work in the future. Did you mean "\\_"? A raw string is also an option.
  dados = pd.read_excel('C:\_Master\programacao\Guilherme-Betta\IC2\data\in\dadosBrutos.xlsx')

<bound method DataFrame.info of           Data Estatistica    COR  TURB.   pH  ALC.   AC.  O.C.  DBO  O.D.  \
0   2009-01-01        Min.  200.0   64.0  7.0  29.0   3.0   6.3  NaN   2.0
1   2009-01-01        Med.  432.0  131.0  7.2  34.0   5.0   6.8  NaN   3.5
2   2009-01-01        Max.  690.0  241.0  7.4  38.0   8.0   7.5  NaN   4.8
3   2009-02-01        Min.  393.0   72.0  6.5  29.0   6.0   5.9  NaN   2.8
4   2009-02-01        Med.  868.0  238.0  7.1  31.0   7.0   7.2  NaN   4.1
..         ...         ...    ...    ...  ...   ...   ...   ...  ...   ...
571 2024-11-01        Med.  217.0  134.0  7.5  48.0   9.0   9.7  NaN   4.2
572 2024-11-01        Max.  805.0  746.0  7.8  60.0  18.0  17.6  NaN   6.0
573 2024-12-01        Min.    NaN    NaN  NaN   NaN   NaN   NaN  NaN   NaN
574 2024-12-01        Med.    NaN    NaN  NaN   NaN   NaN   NaN  NaN   NaN
575 2024-12-01        Max.    NaN    NaN  NaN   NaN   NaN   NaN  NaN   NaN

     ...  Cond.  Amonia   Surfact.  Cianobacteria  S.T.      C.T.   C.F.  \
0    ...  131.0      NaN       NaN         6600.0   NaN   50000.0  23000
1    ...  145.0      NaN       NaN         6850.0   NaN   50000.0  23000
2    ...  156.0      NaN       NaN         7100.0   NaN   50000.0  23000
3    ...  128.0      NaN       NaN         1100.0   NaN  240000.0  30000
4    ...  133.0      NaN       NaN         2100.0   NaN  240000.0  30000
..   ...    ...      ...       ...            ...   ...       ...    ...
571  ...  263.0     2.00       NaN            NaN   NaN       NaN   3000
572  ...  439.0     4.39       NaN            NaN   NaN       NaN   3000
573  ...    NaN      NaN       NaN            NaN   NaN       NaN    NaN
574  ...    NaN      NaN       NaN            NaN   NaN       NaN    NaN
575  ...    NaN      NaN       NaN            NaN   NaN       NaN    NaN

     Clorofila     F  Fenol
0         2.23  0.12    NaN
1        11.35  0.16    NaN
2        22.32  0.19    NaN
3         6.69  0.12    NaN
4         7.81  0.16    NaN
..         ...   ...    ...
571      38.68  0.32    NaN
572      38.68  0.42    NaN
573        NaN   NaN    NaN
574        NaN   NaN    NaN
575        NaN   NaN    NaN

[576 rows x 26 columns]>

In [ ]:
describe = dados.describe()

describe['Totais'] = describe[dados.sum(axis=1) if str(dados[].dt).startswith() != float ]

print(describe)

               COR        TURB.          pH        ALC.         AC.  \
count   575.000000   575.000000  575.000000  548.000000  548.000000
mean    148.740035   101.870470    7.298122   63.467500   12.558741
std     192.111250   196.266998    0.443058   30.932143   11.728050
min       0.520000     0.520000    0.520000    5.190000    0.000000
25%      46.000000     9.000000    7.200000   43.000000    7.000000
50%      74.000000    21.000000    7.300000   57.000000   10.000000
75%     171.000000    92.000000    7.500000   75.250000   13.000000
max    1650.000000  1200.000000    8.100000  224.000000  120.000000

             O.C.         DBO        O.D.          Cl        DUR.  ...  \
count  557.000000   23.000000  562.000000  557.000000  557.000000  ...
mean     9.076355   43.257391    3.267740   45.142962   54.997540  ...
std      5.725200  115.610739    1.689918   31.002758   23.931064  ...
min      2.300000    1.600000    0.000000    3.630000    3.630000  ...
25%      6.300000    5.100000    2.100000   29.000000   40.000000  ...
50%      7.800000    6.900000    3.100000   39.000000   50.000000  ...
75%     10.200000   10.100000    4.300000   51.000000   64.000000  ...
max     84.000000  555.000000   16.000000  328.000000  174.000000  ...

                N           P        Cond.     Amonia     Surfact.  \
count   65.000000   56.000000   569.000000  143.000000    5.000000
mean    16.842000   11.629821   324.544042    7.501818  134.503400
std     63.827936   70.466615   181.142098   36.634136  248.847335
min      2.070000    0.060000     1.560000    0.000000    0.129000
25%      3.450000    0.300000   202.000000    1.355000    0.129000
50%      6.820000    0.800000   283.000000    3.100000    0.129000
75%      9.610000    0.952500   403.000000    6.190000   99.130000
max    513.000000  522.000000  1438.000000  435.000000  573.000000

       Cianobacteria        S.T.          C.T.   Clorofila           F
count     536.000000    5.000000  2.270000e+02  533.000000  470.000000
mean    10488.209459  221.426000  3.032694e+05   36.498780    0.581740
std     14944.605926  197.536952  5.401186e+05   47.681777    5.041256
min         7.270000   99.130000  0.000000e+00    0.000000    0.000000
25%      2007.000000  145.000000  3.000000e+04   12.280000    0.200000
50%      4961.500000  145.000000  9.000000e+04   25.290000    0.280000
75%     13364.000000  145.000000  3.000000e+05   46.130000    0.380000
max    122480.000000  573.000000  3.000000e+06  509.640000  108.000000

[8 rows x 22 columns]

In [11]:
### Dados Ausentes

def calculate_missing_percentage(df1, df2):
    missing_by_column = df1.isna().sum()
    total_rows = len(df1)
    missing_percentage_by_column = (missing_by_column / total_rows * 100).round(2)
    missing_total = df1.isna().sum().sum()
    total_elements = df1.size
    missing_percentage_total = (missing_total / total_elements * 100).round(2)
    df2.loc["Porcentagem de Dados Faltantes"] = missing_percentage_by_column
    df2.loc["Numero de Dados Faltantes"] = missing_by_column
    return {
        'by_column': missing_percentage_by_column,
        'total': missing_percentage_total
    }

In [ ]:
calculate_missing_percentage(dados, describe)

,Data,COR,TURB.,pH,ALC.,AC.,O.C.,DBO,O.D.,Cl,...,N,P,Cond.,Amonia,Surfact.,Cianobacteria,S.T.,C.T.,Clorofila,F
count,576,573.000000,573.000000,573.000000,546.000000,546.000000,555.000000,21.00000,560.000000,555.000000,...,63.000000,54.000000,567.000000,141.000000,3.000,534.000000,3.0,2.250000e+02,531.000000,468.000000
mean,2016-12-15 17:00:00,149.253054,102.219895,7.317452,63.635531,12.540293,9.064685,16.37619,3.245893,45.261261,...,7.825079,0.721481,325.670194,3.989362,0.129,10527.398876,145.0,3.059633e+05,36.536836,0.313521
min,2009-01-01 00:00:00,4.000000,1.000000,4.700000,16.000000,0.000000,2.300000,1.60000,0.000000,5.000000,...,2.070000,0.060000,60.000000,0.000000,0.129,57.000000,145.0,0.000000e+00,0.000000,0.000000
25%,2012-12-24 06:00:00,46.000000,9.000000,7.200000,44.000000,7.000000,6.300000,4.60000,2.100000,30.000000,...,3.450000,0.300000,202.500000,1.350000,0.129,2064.000000,145.0,3.000000e+04,12.280000,0.197500
50%,2016-12-16 12:00:00,74.000000,21.000000,7.300000,57.500000,10.000000,7.800000,6.20000,3.100000,39.000000,...,6.820000,0.800000,283.000000,3.050000,0.129,4964.000000,145.0,9.000000e+04,25.290000,0.280000
75%,2020-12-08 18:00:00,171.000000,92.000000,7.500000,75.750000,13.000000,10.200000,9.80000,4.300000,51.000000,...,8.400000,0.930000,403.000000,6.130000,0.129,13364.000000,145.0,3.000000e+05,47.170000,0.380000
max,2024-12-01 00:00:00,1650.000000,1200.000000,8.100000,224.000000,120.000000,84.000000,102.00000,9.500000,328.000000,...,42.700000,1.620000,1438.000000,13.000000,0.129,122480.000000,145.0,3.000000e+06,509.640000,1.520000
std,NaN,192.249766,196.520361,0.289820,30.854392,11.721510,5.708409,26.65481,1.604717,30.991355,...,8.299457,0.456746,180.463045,3.259131,0.000,14958.841172,0.0,5.417615e+05,47.753936,0.201867

In [16]:
pasta_saida = "C:\_Master\programacao\Guilherme-Betta\IC2\data\out" # Cria uma variável para guardar o caminho de onde o arquivo resultante será salvo

os.makedirs(pasta_saida, exist_ok=True) # Passo necessário para o python salvar o arquivo

nome_arquivo = f"describe()_{datetime.now().strftime('%Y%m%d_%H%M%S')}.xlsx"   # Gera o nome do arquivo de saida com timestamp de quando foi criado

caminho_saida = os.path.join(pasta_saida, nome_arquivo) # Cria o diretório para salvar o arquivo caso ela ainda não exista

describe.to_excel(caminho_saida, engine='openpyxl', index=True)   # Gera o arquivo de saida

<>:1: SyntaxWarning: "\_" is an invalid escape sequence. Such sequences will not work in the future. Did you mean "\\_"? A raw string is also an option.
<>:1: SyntaxWarning: "\_" is an invalid escape sequence. Such sequences will not work in the future. Did you mean "\\_"? A raw string is also an option.
C:\Users\Wary\AppData\Local\Temp\ipykernel_26316\1168293534.py:1: SyntaxWarning: "\_" is an invalid escape sequence. Such sequences will not work in the future. Did you mean "\\_"? A raw string is also an option.
  pasta_saida = "C:\_Master\programacao\Guilherme-Betta\IC2\data\out" # Cria uma variável para guardar o caminho de onde o arquivo resultante será salvo

In [23]:
dados.select_dtypes(exclude= float)   # Permite identificar colunas com valores nao numericos. 
                                            # No caso, sao elas "Data" e "data_normalizada" (esperado), 
                                            # mas tambem "C.F. Max.", "Fenol_Max.", "Fenol_Med." e "Fenol_Min."
                                            # Isso ocorre, pois essas colunas apresentam células com os caracteres "<" ou ">"

          Data Estatistica   C.F. Fenol
0   2009-01-01        Min.  23000   NaN
1   2009-01-01        Med.  23000   NaN
2   2009-01-01        Max.  23000   NaN
3   2009-02-01        Min.  30000   NaN
4   2009-02-01        Med.  30000   NaN
..         ...         ...    ...   ...
571 2024-11-01        Med.   3000   NaN
572 2024-11-01        Max.   3000   NaN
573 2024-12-01        Min.    NaN   NaN
574 2024-12-01        Med.    NaN   NaN
575 2024-12-01        Max.    NaN   NaN

[576 rows x 4 columns]