# Set Up

In [11]:
import pandas as pd
import numpy as np
from pcj.utils import dados
from pcj.processamento import decompor_estatisticas
from pcj.outliers import detect_outliers_zscore, detect_outliers_iqr, resumo_por_mes

In [2]:
df, metadados, variaveis = dados(r"data\processed\dados_limpos.xlsx")
df_med = decompor_estatisticas(df, estatistica="med")

Verificação do efeito da transformação logarítmica

In [10]:
df_med[variaveis].skew()

COR              3.431387
TURB.            1.982049
pH               0.640509
ALC.             1.800605
AC.              3.818553
O.C.             2.850822
O.D.             0.181960
Cl               3.915182
DUR.             1.407600
Fe               2.665936
Mn               2.408677
Cond.            1.524526
Cianobacteria    3.639978
C.F.             3.765265
Clorofila        6.107537
F                0.629216
dtype: float64

In [12]:
np.log1p(df_med[variaveis]).skew()

COR              0.498347
TURB.            0.256828
pH               0.569107
ALC.             0.386058
AC.              1.523625
O.C.             0.759782
O.D.            -0.693960
Cl               0.854930
DUR.            -0.111096
Fe               0.946183
Mn               2.037038
Cond.            0.145859
Cianobacteria   -0.258637
C.F.            -0.618300
Clorofila       -0.081824
F                0.114069
dtype: float64

# Z-Score

In [3]:
limites_z, total_z, mascara_z = detect_outliers_zscore(df_med, variaveis, verbose=True)
limites_z

Total de outliers (Z-Score, somando todas as colunas): 52
Total de linhas com pelo menos um outlier (Z-Score): 30

               limite_inferior  limite_superior  n_outliers
COR                -209.678710       450.631590           3
TURB.              -165.188988       292.340820           3
pH                    6.784348         7.864867           3
ALC.                -16.999291       143.845444           5
AC.                 -15.508805        39.981332           4
O.C.                 -0.125862        17.205862           3
O.D.                  0.469263         5.769240           0
Cl                  -35.333001       124.716785           3
DUR.                  1.234158       106.711788           2
Fe                   -3.701493         8.009709           4
Mn                   -0.172778         0.553103           7
Cond.              -149.073825       803.973296           3
Cianobacteria    -33922.154763     54963.817684           3
C.F.            -127038.671849    175017.632888           4
Clorofila          -106.469596       179.515133           2
F                    -0.115160         0.705776           3

In [4]:
limites_z_log, total_z_log, mascara_z_log = detect_outliers_zscore(df_med, variaveis, log=True, verbose=True)
limites_z_log

Total de outliers (Z-Score, somando todas as colunas): 32
Total de linhas com pelo menos um outlier (Z-Score): 22

               limite_inferior  limite_superior  n_outliers
COR                  10.455819     7.529917e+02           2
TURB.                 0.099675     1.060523e+03           0
pH                    6.802833     7.877152e+00           3
ALC.                 18.722207     1.811609e+02           1
AC.                   2.044521     4.354708e+01           4
O.C.                  3.259408     1.889550e+01           3
O.D.                  1.040214     6.921207e+00           2
Cl                   10.601946     1.453528e+02           2
DUR.                 19.893110     1.306497e+02           2
Fe                   -0.335685     1.053610e+01           1
Mn                   -0.101401     5.621272e-01           7
Cond.                75.817449     1.141754e+03           0
Cianobacteria       104.514758     2.402423e+05           1
C.F.                 36.239462     1.135333e+06           1
Clorofila             0.657169     3.697635e+02           2
F                    -0.057907     7.615818e-01           1

In [5]:
_, total_zscore_log, mascara_zscore_log = detect_outliers_zscore(df_med, variaveis, log=True)
resumo_por_mes(df_med, mascara_zscore_log)

          Data  n_variaveis                 variaveis
202 2014-08-01            4     ALC., AC., O.C., O.D.
34  2009-12-01            2                   COR, Fe
184 2014-02-01            2             pH, Clorofila
211 2014-11-01            2                     Cl, F
208 2014-10-01            2                    pH, Cl
205 2014-09-01            2                  pH, O.C.
319 2017-11-01            2                   AC., Mn
286 2016-12-01            2  Cianobacteria, Clorofila
4   2009-02-01            1                       COR
61  2010-09-01            1                      O.D.
199 2014-07-01            1                       AC.
247 2015-11-01            1                        Mn
283 2016-11-01            1                        Mn
256 2016-02-01            1                      DUR.
298 2017-04-01            1                      O.C.
301 2017-05-01            1                      C.F.
310 2017-08-01            1                        Mn
313 2017-09-01            1                        Mn
325 2018-01-01            1                        Mn
337 2018-05-01            1                      DUR.
496 2022-10-01            1                       AC.
508 2023-02-01            1                        Mn

# IQR

In [6]:
limites_iqr, total_iqr, mascara_iqr = detect_outliers_iqr(df_med, variaveis, verbose=True)
limites_iqr

Total de outliers (IQR, somando todas as colunas): 181
Total de linhas com pelo menos um outlier (IQR): 89

               limite_inferior  limite_superior  n_outliers
COR                    -93.250          300.750           7
TURB.                 -108.500          207.500          14
pH                       6.900            7.700           4
ALC.                     5.500          113.500          11
AC.                      2.000           18.000          21
O.C.                     2.750           13.550           5
O.D.                     0.775            5.375           4
Cl                       3.500           79.500          13
DUR.                    10.500           94.500           6
Fe                      -1.810            5.470          11
Mn                      -0.015            0.345          17
Cond.                  -70.500          677.500           6
Cianobacteria       -14599.125        29713.875          15
C.F.                -22687.500        44012.500          20
Clorofila              -38.495           96.905          11
F                        0.010            0.570          16

In [7]:
resumo_por_mes(df_med, mascara_iqr)

          Data  n_variaveis                                        variaveis
202 2014-08-01            9  ALC., AC., O.C., O.D., Cl, DUR., Cond., C.F., F
205 2014-09-01            8           pH, ALC., O.C., Cl, DUR., Mn, Cond., F
208 2014-10-01            6                  pH, ALC., Cl, DUR., Cond., C.F.
211 2014-11-01            6                     ALC., Cl, Mn, Cond., C.F., F
199 2014-07-01            5                       ALC., AC., Cl, Cond., C.F.
..         ...          ...                                              ...
511 2023-03-01            1                                              AC.
517 2023-05-01            1                                             DUR.
514 2023-04-01            1                                              AC.
556 2024-06-01            1                                              AC.
526 2023-08-01            1                                    Cianobacteria

[89 rows x 3 columns]

In [8]:
limites_iqr_log, total_iqr_log, mascara_iqr_log = detect_outliers_iqr(df_med, variaveis, log=True, verbose=True)
limites_iqr_log

Total de outliers (IQR, somando todas as colunas): 81
Total de linhas com pelo menos um outlier (IQR): 52

               limite_inferior  limite_superior  n_outliers
COR                  11.007767       710.700376           2
TURB.                -0.529281      2100.086118           0
pH                    6.908893         7.709183           4
ALC.                 22.790144       145.194998           4
AC.                   4.184313        21.568080          18
O.C.                  3.994046        15.399528           4
O.D.                  1.285748         6.119796           2
Cl                   15.683218       101.857852           7
DUR.                 22.681062       115.211004           3
Fe                   -0.293771         9.167804           3
Mn                   -0.002605         0.358740          14
Cond.                80.448207      1030.060139           1
Cianobacteria       121.224318    216365.827138           1
C.F.                 98.580447    443748.512413           1
Clorofila             0.986319       314.098610           3
F                     0.036552         0.600691          14

In [9]:
resumo_por_mes(df_med, mascara_iqr_log)

          Data  n_variaveis                     variaveis
202 2014-08-01            6  ALC., AC., O.C., O.D., Cl, F
205 2014-09-01            6     pH, ALC., O.C., Cl, Mn, F
208 2014-10-01            4           pH, ALC., Cl, Cond.
199 2014-07-01            3                 ALC., AC., Cl
211 2014-11-01            3                     Cl, Mn, F
301 2017-05-01            3                  AC., C.F., F
508 2023-02-01            3                   AC., Cl, Mn
184 2014-02-01            2                 pH, Clorofila
286 2016-12-01            2      Cianobacteria, Clorofila
256 2016-02-01            2                      Cl, DUR.
34  2009-12-01            2                       COR, Fe
4   2009-02-01            2                       COR, Fe
310 2017-08-01            2                       AC., Mn
319 2017-11-01            2                       AC., Mn
565 2024-09-01            2                       pH, AC.
250 2015-12-01            1                             F
133 2012-09-01            1                           AC.
187 2014-03-01            1                            Mn
73  2011-01-01            1                            Fe
61  2010-09-01            1                          O.D.
289 2017-01-01            1                     Clorofila
283 2016-11-01            1                            Mn
268 2016-06-01            1                            Mn
253 2016-01-01            1                          O.C.
247 2015-11-01            1                            Mn
298 2017-04-01            1                          O.C.
304 2017-06-01            1                           AC.
292 2017-02-01            1                            Mn
337 2018-05-01            1                          DUR.
340 2018-06-01            1                          DUR.
349 2018-09-01            1                             F
355 2018-11-01            1                           AC.
358 2018-12-01            1                           AC.
361 2019-01-01            1                           AC.
313 2017-09-01            1                            Mn
325 2018-01-01            1                            Mn
385 2019-09-01            1                             F
379 2019-07-01            1                           AC.
391 2019-11-01            1                            Mn
400 2020-02-01            1                            Mn
421 2020-09-01            1                             F
424 2020-10-01            1                             F
415 2020-07-01            1                             F
418 2020-08-01            1                             F
430 2020-12-01            1                             F
427 2020-11-01            1                             F
484 2022-06-01            1                           AC.
457 2021-09-01            1                             F
496 2022-10-01            1                           AC.
514 2023-04-01            1                           AC.
556 2024-06-01            1                           AC.
562 2024-08-01            1                           AC.